#!/bin/bash
# Quick reference for TooLoo.ai commands

echo "╔══════════════════════════════════════════════════╗"
echo "║        TooLoo.ai - Quick Command Reference       ║"
echo "╚══════════════════════════════════════════════════╝"
echo ""
echo "🚀 START TOOLOO"
echo "   npm start"
echo ""
echo "🧪 TEST SYSTEM"
echo "   npm test"
echo ""
echo "🏗️  BUILD FRONTEND"
echo "   npm run build"
echo ""
echo "🏥 CHECK API HEALTH"
echo "   npm run health"
echo ""
echo "🎨 ACCESS UI"
echo "   http://localhost:5173"
echo "   (Or click globe icon on port 5173 in VS Code)"
echo ""
echo "🛑 STOP SERVERS"
echo "   Ctrl+C (in terminal where npm start is running)"
echo ""
echo "═══════════════════════════════════════════════════"
echo ""
