#!/bin/bash

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🚀 TooLoo.ai - CLICK THIS URL TO ACCESS YOUR APP:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "👉 https://fluffy-doodle-q7gg7rx5wrxjh9v77-5173.app.github.dev"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Instructions:"
echo "1. Ctrl+Click (or Cmd+Click) on the URL above"
echo "2. Or copy-paste it into your browser"
echo "3. You should see the DARK THEME interface"
echo ""
echo "If you see 'Not Found':"
echo "• Make sure servers are running (npm start)"
echo "• Try hard refresh: Ctrl+Shift+R"
echo ""
