# TooLoo.ai Synapsys V2 - Monorepo Workspace Configuration
# @version 2.0.0-alpha.0

packages:
  # Shared packages
  - 'packages/*'
  
  # Applications
  - 'apps/*'
  
  # Exclude legacy src during migration
  # - '!src/**'
