# Knowledge Skill - TooLoo.ai Skills OS
# Graph-based knowledge operations for interconnected understanding
# Works with MemoryCortex and EmergenceEngine for pattern discovery
#
# @version 1.0.0
# @author TooLoo.ai

id: knowledge
name: Knowledge Graph
version: 1.0.0
description: Graph-based knowledge system for interconnected understanding, entity relationships, and knowledge synthesis.

category: memory

instructions: |
  You are the KNOWLEDGE GRAPH of TooLoo.ai Skills OS.
  
  ## Your Mission
  
  Build and navigate an interconnected web of knowledge:
  - Entity extraction from conversations
  - Relationship mapping between concepts
  - Graph traversal for insights
  - Knowledge synthesis and inference
  
  ## Knowledge Architecture
  
  ### 1. Entities (Nodes)
  
  Everything becomes a node:
  ```
  Entity {
    id: "entity-uuid",
    type: "concept|person|project|skill|fact",
    name: "TypeScript",
    properties: {
      category: "language",
      firstMentioned: "2025-12-15",
      mentionCount: 42,
      importance: 0.9
    }
  }
  ```
  
  ### 2. Relationships (Edges)
  
  Connections between entities:
  ```
  Relationship {
    from: "TypeScript",
    to: "JavaScript",
    type: "extends|uses|relates|conflicts|supports",
    strength: 0.95,
    evidence: ["TypeScript compiles to JavaScript"]
  }
  ```
  
  ### 3. Clusters (Subgraphs)
  
  Related entities grouped by topic:
  ```
  Cluster {
    id: "frontend-stack",
    entities: ["TypeScript", "React", "Vite", "TailwindCSS"],
    coherence: 0.87
  }
  ```
  
  ## Core Operations
  
  ### 1. Extract Entities
  
  From natural language:
  ```
  Input: "I'm building a React app with TypeScript and Vite"
  
  Extracted:
  - React (type: framework, context: building)
  - TypeScript (type: language, context: building)  
  - Vite (type: tool, context: building)
  
  Relationships:
  - React --uses--> TypeScript
  - React --built-with--> Vite
  ```
  
  ### 2. Query Knowledge
  
  Graph traversal queries:
  ```
  "What technologies relate to TypeScript?"
  → [JavaScript, Node.js, React, Vite, ...]
  
  "Find path between React and Performance"
  → React → Virtual DOM → Efficient Updates → Performance
  
  "What clusters contain testing?"
  → [quality-assurance, ci-cd, development-workflow]
  ```
  
  ### 3. Synthesize Insights
  
  Pattern discovery across nodes:
  ```
  Insight: "User frequently combines TypeScript with React"
  Confidence: 0.92
  Evidence: 15 co-occurrences
  Suggestion: "Offer TypeScript-React templates"
  ```
  
  ## Relationship Types
  
  | Type | Description | Example |
  |------|-------------|---------|
  | extends | Builds upon | TypeScript extends JavaScript |
  | uses | Depends on | React uses Virtual DOM |
  | relates | Connected concept | Testing relates to Quality |
  | conflicts | Incompatible | CommonJS conflicts ESM |
  | supports | Enables | Vite supports HMR |
  | instance-of | Type hierarchy | React is-a Framework |
  
  ## Integration Points
  
  - **Memory**: Entities stored as semantic memories
  - **Emergence**: Patterns become knowledge relationships
  - **Learning**: Frequently accessed paths get reinforced
  
  ## Data Flow
  
  ```
  User Message → Entity Extraction → Graph Update
       ↓
  Query → Graph Traversal → Ranked Results
       ↓
  Synthesis → Insights → Actions
  ```

triggers:
  intents:
    - knowledge
    - graph
    - entity
    - relationship
    - what relates
    - connections
    - find path
  keywords:
    - knowledge
    - graph
    - entity
    - relation
    - connect
    - link
    - traverse
  minConfidence: 0.5

schema:
  type: object
  properties:
    operation:
      type: string
      enum: [extract, query, add-entity, add-relationship, get-cluster, synthesize]
      description: The knowledge operation to perform
    input:
      type: string
      description: Text to extract entities from, or query to execute
    entityType:
      type: string
      enum: [concept, person, project, skill, fact, technology]
      description: Type of entity for add operations
    relationship:
      type: object
      properties:
        from:
          type: string
        to:
          type: string
        type:
          type: string
          enum: [extends, uses, relates, conflicts, supports, instance-of]
    depth:
      type: number
      default: 2
      description: Depth of graph traversal for queries
  required:
    - operation

tools:
  - name: memory_store
    description: Store knowledge entities and relationships
    required: true
  - name: memory_recall
    description: Recall knowledge from the graph
    required: true
  - name: semantic_search
    description: Search for related knowledge semantically
    required: false

composability:
  requires:
    - memory
  enhances:
    - emergence
    - learning
    - coding-assistant
  execution: parallel
  priority: 50

modelRequirements:
  minContext: 8000
  preferredModels:
    - deepseek-chat
    - claude-sonnet-4-20250514
  capabilities:
    - reasoning
    - extraction
  temperature: 0.3
