import fetch from 'node-fetch';// @version 2.1.245














































main();}    }        console.error('Bridge Error:', error);    } catch (error) {        }                console.log('Unknown command');            default:                break;                console.log(await res.json());                });                    })                        createPr: createPr === 'true'                        message,                        content,                        file,                        action: 'update',                    body: JSON.stringify({                    headers: { 'Content-Type': 'application/json' },                    method: 'POST',                const res = await fetch(`${API_URL}/system/self-patch`, {                const [file, content, message, createPr] = args;                // Usage: patch <file> <content> <message> [createPr]            case 'patch':                            break;                console.log(JSON.stringify(status, null, 2));                const status = await fetch(`${API_URL}/system/awareness`).then(r => r.json());            case 'status':        switch (command) {    try {    }        return;        console.log('Usage: tsx scripts/bridge.ts <command> [args]');    if (!command) {    const args = process.argv.slice(3);    const command = process.argv[2];async function main() {const API_URL = 'http://127.0.0.1:4000/api/v1';