#!/bin/bash

# Smart Intelligence Analytics - Quick Reference Card
# Fast access to common operations

echo "📊 Smart Intelligence Analytics - Quick Reference"
echo "=================================================="
echo ""
echo "🚀 QUICK START"
echo "  npm run start:web                    # Start web server"
echo "  http://127.0.0.1:3000/smart-intelligence-analytics-dashboard.html"
echo ""
echo "📡 API ENDPOINTS (all on port 3000)"
echo "  Summary Stats (30 days default):"
echo "    curl http://127.0.0.1:3000/api/v1/smart-intelligence/analytics/summary?days=30"
echo ""
echo "  Confidence Trend (7 days default):"
echo "    curl http://127.0.0.1:3000/api/v1/smart-intelligence/analytics/trend?days=7"
echo ""
echo "  Action Statistics (30 days default):"
echo "    curl http://127.0.0.1:3000/api/v1/smart-intelligence/analytics/actions?days=30"
echo ""
echo "  Export as CSV:"
echo "    curl 'http://127.0.0.1:3000/api/v1/smart-intelligence/analytics/export/csv?days=30' -o patterns.csv"
echo ""
echo "  Export as JSON:"
echo "    curl 'http://127.0.0.1:3000/api/v1/smart-intelligence/analytics/export/json?days=30' -o patterns.json"
echo ""
echo "📂 DATA LOCATION"
echo "  Patterns: /workspaces/TooLoo.ai/data/validation-patterns/"
echo "  View today: cat data/validation-patterns/patterns_$(date +%Y-%m-%d).json | jq ."
echo ""
echo "📚 DOCUMENTATION"
echo "  Integration Guide: SMART-INTELLIGENCE-ANALYTICS-INTEGRATION.md"
echo "  Quick Start: SMART-INTELLIGENCE-ANALYTICS-QUICKSTART.md"
echo "  Implementation: SMART-INTELLIGENCE-ANALYTICS-IMPLEMENTATION-COMPLETE.md"
echo ""
echo "🔍 TROUBLESHOOTING"
echo "  Check service health:"
echo "    curl http://127.0.0.1:3000/api/v1/smart-intelligence/analytics/summary"
echo ""
echo "  View raw patterns:"
echo "    ls -la data/validation-patterns/"
echo ""
echo "  Check file size:"
echo "    du -sh data/validation-patterns/"
echo ""
echo "💡 COMMON TASKS"
echo "  Get yesterday's patterns:"
echo "    cat data/validation-patterns/patterns_$(date -d yesterday +%Y-%m-%d).json"
echo ""
echo "  Find high-confidence validations:"
echo "    cat data/validation-patterns/patterns_*.json | jq '.[] | select(.confidenceScore > 90)'"
echo ""
echo "  Count total patterns:"
echo "    cat data/validation-patterns/patterns_*.json | jq 'length' | paste -sd+ | bc"
echo ""
echo "🎯 KEY METRICS"
echo "  ✓ totalValidations       - Number of patterns analyzed"
echo "  ✓ averageConfidence      - 0-100% score"
echo "  ✓ confidenceBracket      - critical|high|moderate|low|unverified"
echo "  ✓ recommendedAction      - accept|use with caution|review|revise"
echo "  ✓ insightCount           - Useful insights identified"
echo "  ✓ gapCount               - Information gaps found"
echo "  ✓ issueCount             - Critical issues detected"
echo "  ✓ processingTime         - Milliseconds to validate"
echo ""
echo "✅ VERIFICATION CHECKLIST"
echo "  [ ] Web server running (npm run start:web)"
echo "  [ ] Dashboard loads (http://127.0.0.1:3000/smart-intelligence-analytics-dashboard.html)"
echo "  [ ] Summary endpoint responds (curl /api/v1/smart-intelligence/analytics/summary)"
echo "  [ ] Data directory exists (ls data/validation-patterns/)"
echo "  [ ] Can export CSV (curl /api/v1/smart-intelligence/analytics/export/csv)"
echo "  [ ] Can export JSON (curl /api/v1/smart-intelligence/analytics/export/json)"
echo ""
echo "📊 DASHBOARD FEATURES"
echo "  • Real-time stat cards"
echo "  • Confidence distribution chart"
echo "  • Action distribution chart"
echo "  • 30-day confidence trend"
echo "  • Top questions list"
echo "  • Time range selector (7/14/30/90 days)"
echo "  • CSV/JSON export buttons"
echo "  • Mobile responsive design"
echo ""
echo "🔗 RELATED COMPONENTS"
echo "  Service: /lib/smart-intelligence-analytics.js"
echo "  Dashboard: /web-app/smart-intelligence-analytics-dashboard.html"
echo "  Web Server: /servers/web-server.js"
echo "  Data: /data/validation-patterns/"
echo ""
echo "💬 NEED HELP?"
echo "  1. Read SMART-INTELLIGENCE-ANALYTICS-QUICKSTART.md"
echo "  2. Check SMART-INTELLIGENCE-ANALYTICS-INTEGRATION.md for API details"
echo "  3. View dashboard at http://127.0.0.1:3000/smart-intelligence-analytics-dashboard.html"
echo "  4. Check web-server logs for [Analytics] messages"
echo ""
echo "✅ STATUS: Production Ready"
echo ""
