// @version 3.3.576
/**
 * @file Plan executor (scaffold generator)
 * @version 1.0.1
 * @skill-os true
 */

import path from 'node:path';
import fs from 'node:fs/promises';
import type { PlanBundle } from '@tooloo/types';

export type ExecuteResult = {
  projectPath: string;
  filesWritten: string[];
};

function sanitizeSlug(input: string): string {
  return input
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/(^-|-$)/g, '')
    .slice(0, 60) || 'genesis-app';
}

async function writeFileEnsuringDir(filePath: string, content: string): Promise<void> {
  await fs.mkdir(path.dirname(filePath), { recursive: true });
  await fs.writeFile(filePath, content, 'utf-8');
}

export async function scaffoldWebApp(args: {
  sessionId: string;
  missionPrompt: string;
  planBundle: PlanBundle;
}): Promise<ExecuteResult> {
  const root = process.env.GENESIS_PROJECTS_DIR
    ? path.resolve(process.env.GENESIS_PROJECTS_DIR)
    : path.resolve(process.cwd(), '../../generated');

  const slug = sanitizeSlug('native-english-coach');
  const projectPath = path.join(root, `${slug}-${args.sessionId.slice(0, 8)}`);

  const pkgName = `genesis-${slug}-${args.sessionId.slice(0, 8)}`;

  const files: Array<{ rel: string; content: string }> = [
    {
      rel: 'GENESIS_EXECUTION_PROOF.json',
      content: JSON.stringify(
        {
          generatedAt: new Date().toISOString(),
          sessionId: args.sessionId,
          revision: args.planBundle.revision,
          kind: 'web',
          note: 'This file exists to prove the generator executed and wrote to disk.',
        },
        null,
        2,
      ),
    },
    {
      rel: 'README.md',
      content: `# ${slug} (Generated by TooLoo Genesis)\n\nThis project was scaffolded from a Genesis PlanBundle.\n\n## Mission\n\n${args.missionPrompt}\n\n## What’s included\n- Web-first React + Vite + TypeScript scaffold\n- Minimal app shell with a practice session screen and parent summary stub\n- Content placeholders derived from the plan (PRD/Curriculum/Scripts)\n\n## Next steps\n1. Install deps\n2. Run dev server\n3. Replace placeholders with real curriculum + audio assets\n\n> Note: Genesis will add features iteratively in future execution passes.\n`,
    },
    {
      rel: 'package.json',
      content: JSON.stringify(
        {
          name: pkgName,
          private: true,
          version: '0.0.0',
          type: 'module',
          scripts: {
            dev: 'vite',
            build: 'tsc -b && vite build',
            preview: 'vite preview',
          },
          dependencies: {
            react: '^18.3.1',
            'react-dom': '^18.3.1',
          },
          devDependencies: {
            '@types/react': '^18.3.3',
            '@types/react-dom': '^18.3.0',
            typescript: '^5.3.3',
            vite: '^5.4.21',
            '@vitejs/plugin-react': '^4.3.4',
          },
        },
        null,
        2,
      ),
    },
    {
      rel: 'tsconfig.json',
      content: JSON.stringify(
        {
          compilerOptions: {
            target: 'ES2020',
            useDefineForClassFields: true,
            lib: ['ES2020', 'DOM', 'DOM.Iterable'],
            module: 'ESNext',
            skipLibCheck: true,
            moduleResolution: 'Bundler',
            resolveJsonModule: true,
            isolatedModules: true,
            noEmit: true,
            jsx: 'react-jsx',
            strict: true,
          },
          include: ['src'],
        },
        null,
        2,
      ),
    },
    {
      rel: 'vite.config.ts',
      content: `import { defineConfig } from 'vite';\nimport react from '@vitejs/plugin-react';\n\nexport default defineConfig({\n  plugins: [react()],\n  server: {\n    port: 5178,\n  },\n});\n`,
    },
    {
      rel: 'index.html',
      content: `<!doctype html>\n<html lang=\"en\">\n  <head>\n    <meta charset=\"UTF-8\" />\n    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\n    <title>Genesis App</title>\n  </head>\n  <body>\n    <div id=\"root\"></div>\n    <script type=\"module\" src=\"/src/main.tsx\"></script>\n  </body>\n</html>\n`,
    },
    {
      rel: 'src/main.tsx',
      content: `import React from 'react';\nimport ReactDOM from 'react-dom/client';\nimport { App } from './ui/App';\n\nReactDOM.createRoot(document.getElementById('root')!).render(\n  <React.StrictMode>\n    <App />\n  </React.StrictMode>,\n);\n`,
    },
    {
      rel: 'src/ui/App.tsx',
      content: `import React from 'react';\n\nconst shell: React.CSSProperties = {\n  fontFamily: 'ui-sans-serif, system-ui',\n  maxWidth: 920,\n  margin: '0 auto',\n  padding: 24,\n};\n\nconst card: React.CSSProperties = {\n  border: '1px solid rgba(0,0,0,0.12)',\n  borderRadius: 12,\n  padding: 16,\n  marginTop: 16,\n};\n\nexport function App() {\n  const [screen, setScreen] = React.useState<'home' | 'session' | 'parent'>('home');\n\n  return (\n    <div style={shell}>\n      <h1 style={{ margin: 0 }}>Native’s English Coach</h1>\n      <p style={{ opacity: 0.75, marginTop: 8 }}>Generated by TooLoo Genesis — scaffold v0</p>\n\n      <div style={{ display: 'flex', gap: 8, marginTop: 16, flexWrap: 'wrap' }}>\n        <button onClick={() => setScreen('home')}>Home</button>\n        <button onClick={() => setScreen('session')}>Practice Session</button>\n        <button onClick={() => setScreen('parent')}>Parent Summary</button>\n      </div>\n\n      {screen === 'home' && (\n        <div style={card}>\n          <h2 style={{ marginTop: 0 }}>Mission</h2>\n          <p style={{ whiteSpace: 'pre-wrap' }}>${JSON.stringify(args.missionPrompt)}</p>\n        </div>\n      )}\n\n      {screen === 'session' && (\n        <div style={card}>\n          <h2 style={{ marginTop: 0 }}>Practice Session (Stub)</h2>\n          <p>Warm-up → Teach targets → Drill → Check → Review</p>\n          <details open>\n            <summary>Plan: Scripts (preview)</summary>\n            <pre style={{ whiteSpace: 'pre-wrap' }}>${JSON.stringify(args.planBundle.scriptsMarkdown)}</pre>\n          </details>\n        </div>\n      )}\n\n      {screen === 'parent' && (\n        <div style={card}>\n          <h2 style={{ marginTop: 0 }}>Parent Summary (Stub)</h2>\n          <p>Genesis will generate: weekly summary + recommended at-home practice + approvals.</p>\n          <details>\n            <summary>Plan: Curriculum (preview)</summary>\n            <pre style={{ whiteSpace: 'pre-wrap' }}>${JSON.stringify(args.planBundle.curriculumMarkdown)}</pre>\n          </details>\n        </div>\n      )}\n\n      <div style={card}>\n        <h3 style={{ marginTop: 0 }}>PRD (Preview)</h3>\n        <pre style={{ whiteSpace: 'pre-wrap' }}>${JSON.stringify(args.planBundle.prdMarkdown)}</pre>\n      </div>\n    </div>\n  );\n}\n`,
    },
  ];

  await fs.mkdir(projectPath, { recursive: true });

  const filesWritten: string[] = [];
  for (const f of files) {
    const abs = path.join(projectPath, f.rel);
    await writeFileEnsuringDir(abs, f.content);
    filesWritten.push(f.rel);
  }

  return { projectPath, filesWritten };
}
